# Generated by Django 6.0.7 on 2026-08-06 14:36

from django.db import migrations, models

from partner.avatars import new_avatar_url


def assign_avatars(apps, schema_editor):
    """Give every existing member a picture, one draw each.

    Without this the accounts already in the database keep falling back to the
    initials renderer forever, and the two kinds of member look different for no
    reason a tester could explain.
    """
    PartnerUser = apps.get_model("partner", "PartnerUser")
    for user in PartnerUser.objects.filter(avatar_url=""):
        user.avatar_url = new_avatar_url()
        user.save(update_fields=["avatar_url"])


def clear_avatars(apps, schema_editor):
    """Nothing to undo — the column goes with the field."""


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneruser',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Assigned once at signup and never rewritten. Blank on rows created before avatars existed; those fall back to the local renderer.', max_length=500),
        ),
        migrations.RunPython(assign_avatars, clear_avatars),
    ]
