# Generated by Django 6.0.7 on 2026-08-07 10:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit card')], default='checking', max_length=16)),
                ('number_last4', models.CharField(max_length=4)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('opened_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('dining', 'Dining'), ('transport', 'Transport'), ('bills', 'Bills & utilities'), ('shopping', 'Shopping'), ('income', 'Income'), ('transfer', 'Transfer'), ('fees', 'Fees')], default='shopping', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('pending', 'Pending')], default='posted', max_length=10)),
                ('posted_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='one_primary_account_per_member'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-posted_at'], name='banking_tra_account_05d124_idx'),
        ),
    ]
