# Generated by Django 6.0.7 on 2026-08-06 13:39

import authlib.oauth2.rfc6749.models
import authlib.oidc.core.models
import django.db.models.deletion
import oidc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(max_length=64)),
                ('client_name', models.CharField(max_length=120)),
                ('redirect_uris', models.TextField(help_text='One absolute URL per line. Matched exactly — no wildcards, no prefixes.')),
                ('post_logout_redirect_uris', models.TextField(blank=True, default='')),
                ('scope', models.CharField(default='openid profile email', max_length=255)),
                ('grant_types', models.TextField(default='authorization_code\nrefresh_token')),
                ('response_types', models.TextField(default='code')),
                ('token_endpoint_auth_method', models.CharField(default='client_secret_basic', max_length=64)),
                ('id_token_signed_response_alg', models.CharField(default='RS256', max_length=16)),
                ('is_trusted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAuth2 client',
            },
            bases=(models.Model, authlib.oauth2.rfc6749.models.ClientMixin),
        ),
        migrations.CreateModel(
            name='OAuth2AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('redirect_uri', models.TextField(default='')),
                ('response_type', models.TextField(default='')),
                ('scope', models.TextField(default='')),
                ('nonce', models.CharField(blank=True, default='', max_length=255)),
                ('code_challenge', models.CharField(blank=True, default='', max_length=255)),
                ('code_challenge_method', models.CharField(blank=True, default='', max_length=16)),
                ('auth_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth2 authorization code',
            },
            bases=(models.Model, authlib.oidc.core.models.AuthorizationCodeMixin),
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('token_type', models.CharField(default='Bearer', max_length=40)),
                ('access_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('scope', models.TextField(default='')),
                ('issued_at', models.IntegerField(default=oidc.models.now_ts)),
                ('expires_in', models.IntegerField(default=0)),
                ('revoked_at', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth2 token',
            },
            bases=(models.Model, authlib.oauth2.rfc6749.models.TokenMixin),
        ),
    ]
